driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
verifier:
  name: inspec
  sudo_command: . /etc/profile;
platforms:
- name: centos-6.6
suites:
- name: default
  run_list:
  - recipe[RepeatMasker::default]
  attributes:
