---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec
  # sudo: false # if 'true' (default) inSpec will run tests as 'root', rather than 'kitchen'
  format: doc

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[RepeatMasker::default]
    attributes:
